MONGODB_HOST: mongodb-{{ env }}.devops86s.site # mongodb-dev.devops86s.site
REDIS_HOST: redis-{{ env }}.devops86s.site
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.devops86s.site
CART_HOST: cart.backend-alb-{{ env }}.devops86s.site
USER_HOST: user.backend-alb-{{ env }}.devops86s.site
RABBITMQ_HOST: rabbitmq-{{ env }}.devops86s.site
MYSQL_HOST: mysql-{{ env }}.devops86s.site
SHIPPING_HOST: shipping.backend-alb-{{ env }}.devops86s.site
PAYMENT_HOST: payment.backend-alb-{{ env }}.devops86s.site
